import type { Metadata } from 'next';
import './globals.css';
import dynamic from 'next/dynamic';
import { notFound } from 'next/navigation';
import { hasLocale, NextIntlClientProvider } from 'next-intl';
import { setRequestLocale } from 'next-intl/server';
import ClientComponent from '@/components/client/client-component';
import DynamicImport from '@/components/client/dynamic-import';
import Header from '@/components/common/header';
import { Toaster } from '@/components/ui/sonner';
import { routing } from '@/i18n/routing';

const LogInDialog = dynamic(() => import('@/components/auth/log-in-dialog'), {
  ssr: !!false,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const dynamicParams = false; // required

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({ children, params }: LayoutProps<'/[locale]'>) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);

  return (
    <html lang={locale} suppressHydrationWarning>
      <head>
        <script
          defer
          id='cf-turnstile-script'
          src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit'
        ></script>
        <script src='https://accounts.google.com/gsi/client' async></script>
      </head>
      <body className='dark'>
        <NextIntlClientProvider>
          <Toaster richColors position='top-center' />
          <LogInDialog />
          <Header />
          <DynamicImport />
          <ClientComponent />
          <main className='mx-auto max-w-5xl'>{children}</main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
