import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/common/header';
import dynamic from 'next/dynamic';
import { hasLocale, NextIntlClientProvider } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import { Toaster } from '@/components/ui/sonner';
// import SessionProvider from '@/providers/session-provider';

const LogInDialog = dynamic(() => import('@/components/auth/log-in-dialog'), {
  ssr: !!false,
});

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <head>
        <script
          defer
          id='cf-turnstile-script'
          src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit'
        ></script>
      </head>
      <body className='dark'>
        <NextIntlClientProvider>
          <Toaster richColors position='top-center' />
          <LogInDialog />
          <Header />
          <main className='mx-auto max-w-5xl'>{children}</main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
